# --- !Ups
CREATE TABLE SITES (
  ID   VARCHAR(36) NOT NULL PRIMARY KEY,
  NAME TEXT        NOT NULL
);

CREATE TABLE ARTICLES (
  ARTICLE_ID VARCHAR(36) NOT NULL,
  SITE_ID    VARCHAR(36) NOT NULL,
  PRIMARY KEY (ARTICLE_ID, SITE_ID),
  CONSTRAINT SITE_ID_FK FOREIGN KEY (SITE_ID) REFERENCES SITES (ID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE
);

# --- !Downs
DROP TABLE ARTICLES;
DROP TABLE SITES;