# --- !Ups

CREATE TABLE DISCUSSIONS (
  ID              VARCHAR(36)           NOT NULL PRIMARY KEY,
  TITLE           TEXT                  NOT NULL,
  ALLOW_ANONYMOUS BOOLEAN DEFAULT FALSE NULL
);

CREATE TABLE COMMENTS (
  DISCUSSION_ID VARCHAR(36) NOT NULL,
  COMMENT_ID    BIGINT NOT NULL,
  TEXT          TEXT        NOT NULL,
  COMMENT_BY    VARCHAR(36),
  PRIMARY KEY (DISCUSSION_ID, COMMENT_ID),
  CONSTRAINT DISCUSSION_ID_FK FOREIGN KEY (DISCUSSION_ID) REFERENCES DISCUSSIONS (ID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE
);

CREATE TABLE PROJECTIONS (
  ID       VARCHAR(36) NOT NULL PRIMARY KEY,
  PROGRESS BIGINT      NOT NULL
);

# --- !Downs
DROP TABLE PROJECTIONS;
DROP TABLE COMMENTS;
DROP TABLE DISCUSSIONS;